### ISSUE TITLE
Accessing API from UNITY project 

### ISSUE THREAD

**Issue by gulen-sule** [MineGoksen/Coulomb-s-People#10]
Ülke bazlı sorular, ipuçları ve kullanıcı bilgilerini tuttuğumuz database'imizin üstüne yazdığımız API'ı initialize ettikten sonra Unity projemiz aracılığıyla bu API'a erişmek. Bu task için API'a yapılan bir girdi veya sorgunun ekran görüntüsü ve kodun repository'e pushlanması gerekmektedir.
- Beklenen tamamlanma süresi : 2 hafta

**Comment by AhmedSaidYuksek** [comment]
![Capture4](https://user-images.githubusercontent.com/62549695/229372595-5c0b6420-2ae8-4fcf-9354-d328649a00ed.PNG)
Proje üzerinden erişilen soru gösterilmiştir
