### ISSUE TITLE
Mappilary Street View Show 

### ISSUE THREAD

**Issue by gulen-sule** [MineGoksen/Coulomb-s-People#11]
Street View için kullanılan API'ı gömdükten sonra Unity project içinde API'dan çektiğimiz görseller kullanıcıya sunulacak ve arka planda bu görsellerin koordinat bilgilerine daha sonradan uzaklık hesaplama algoritmasında kullanılmak üzere erişilecektir. 

Bu task için show edilen ekranın görüntüsü ve kodun repository'e pushlanmış olması gerekmektedir. Şekildeki görüntü benzeri bir street view görülmesi beklenmektedir.

<img width="634" alt="Screen Shot 2023-02-11 at 18 46 36" src="https://user-images.githubusercontent.com/91130711/218267456-acfef113-d1ab-4431-b389-66f5a6792f63.png">

- Beklenen tamamlanma süresi : 3 hafta
- Resim kaynağı: https://www.archdaily.com/963797/geoguessr-game-uses-street-view-to-create-a-geographical-puzzle

**Comment by AhmedSaidYuksek** [comment]
Fikir değişikliği yapılmıştır ve yeni spring yapılmıştır.
