### ISSUE TITLE
Google Authentication Research

### ISSUE THREAD

**Issue by MineGoksen** [MineGoksen/Coulomb-s-People#17]
Bu authentication nasıl sağlayabileceğimiz konusunda nelerin yüklenmesi, import edilmesi, kullanıcıdan hangi bilgilerin talep edileceği ve hangi aşamaları sırayla yapılması gerektiği hakkında araştırma yapılacaktır. 
Araştırma detaylı dokümantasyon halinde sunulacaktır.

Tahmini bitirme süresi: 2 hafta

**Comment by gulen-sule** [comment]
uthentication için kullanıcılara kullanım açısından kolaylık sağlaması için Google SDK kullanımı planlanmıştı. Google SDK kullanıcıların deafult browserlarına bağlanarak, o browserda eğer bir Google hesabı ekli ve de aktif ise o kullanıcının bilgilerini alarak  projemiz için üyelik oluşturuyor ve de üye girişini kontrol ederek bizim için session token oluşturacaktı. Fakat projeyi gerçekleme sırasında Google Authentication için SDK kullanımı yapmak istersek Google Play Services’te Developer hesabı oluşturmak gerektiği sorunuyla karşılaştık. Google Play Developer Hesabı bir kerelik ödenen 25 dolarlık bir ücreti gerektirdiği için Google SDK’den vazgeçerek Firebase üzerinden Email/Password temelli bir authentication oluşturduk.

Firebase hesabı bilgileri için lütfen @gulen-sule ile iletişime geçiniz.
<img width="1737" alt="Screenshot 2023-03-12 at 19 17 58" src="https://user-images.githubusercontent.com/80547513/224557758-9245696d-e301-4c87-b51e-0c683dd376c1.png">
