### ISSUE TITLE
Quiz Scene

### ISSUE THREAD

**Issue by MineGoksen** [MineGoksen/Coulomb-s-People#18]
Oyun sonunda sorulan quiz soruları ile kullanıcının puanına ekleme yapılması planlanmaktadır. Bunun için Unity scene olarak eklenecek olan Quiz Soruları gösterimi yapılacaktır. Bunun için dört şıklı quiz sorularının kullanıcıya yöneltilip cevaplarının  alınacağı bir quiz sahnesinin unity içerisinde oluşturululacaktır. Ekranda her defasında bir soru gözükecektir sorunun aşağısında çoktan seçmeli yanıtları dört adet button şeklinde yerleştirilecek ve kullanıcı cevabını uygun olan buttona vr seti ile tıklayarak gerçekleştirecektir. 

Bitmesi için gerekli süre: 3 hafta

**Comment by gulen-sule** [comment]
3D’de Quiz Scene ekranı oluşturulmuştur. Endpointlerden bilgi çekip bu soruları ekranda gösterilmiştir. Bunun için şıklardan doğru veya yanlış döndünüz çıktısına ulaşabilmekteyiz. Çıktı sol alt köşede görülmektedir. Nasıl bir puanlama içereceğimizi belirlemediğimiz için henüz kullanıcıya puan ataması yapmamaktadır.
<img width="1195" alt="Screenshot 2023-03-12 at 19 24 33" src="https://user-images.githubusercontent.com/80547513/224558112-f831b551-59f8-4af4-b6b9-161f1fa93994.png">
