### ISSUE TITLE
locale Storage

### ISSUE THREAD

**Issue by AhmedSaidYuksek** [MineGoksen/Coulomb-s-People#23]
Scene geçişleri sırasında önceki sceneden gerekli olan verilerin locale storagede saklanması sağlanarak bir sonraki scenede kulllanılabile hale getirilmesi araştırılacaktır.
Sign-in'da alınan kullanıcı user idsi sonraki scenede kullanıldığına dair ekran görüntüsü gösterilmeli.

Tahmini teslim: 2 hafta
Ön koşul: sceneler arası geçiş sağlandıktan sonra yapılacaktır.

**Comment by gulen-sule** [comment]
Local storage işlemi gören PlayerPrefs eklenmiş olup authentication'ı sağlamıştır
