### ISSUE TITLE
Assigning points to player and quiz questions

### ISSUE THREAD

**Issue by AhmedSaidYuksek** [MineGoksen/Coulomb-s-People#33]
Oyuncuya verilecek puanların oluşturulması ve quiz sorularından alınacak puanların belirlenilmesi.
Tamamlanması için: Puan verileri paylaşılacak.
Tahmini teslim: 3 hafta

**Comment by berakoksal** [comment]
if (distance < 100)
            score += 125;
        else if (distance < 500)
            score += 100;
        else if (distance < 750)
            score += 75;
        else if (distance < 1000)
            score += 50;
        else if (distance < 1500)
            score += 25;

Tahmin ile gerçek koordinat arası mesafeye göre puan veriliyor, quiz sorusuna doğru cevap vermek %20 bonus ekliyor.
