### ISSUE TITLE
Initialize API 

### ISSUE THREAD

**Issue by gulen-sule** [MineGoksen/Coulomb-s-People#9]
PostgreSQL ile create ettiğimiz database için Python,Flask ile bir API initialize edilmesi. Task tanımı olarak bir Flask projesi oluşturulmuş ve tablelara basic sorgu ve girdiler için endpointler oluşturulmuş olması ve repository'e çalışır halde pushlanmış olması gerekmektedir. 
Erişilen endpointlerin sonuş görüntüleri gösterilecek.

- Beklenen tamamlanma süresi : 3 hafta

**Comment by AhmedSaidYuksek** [comment]
Endpoint noktaları oluşturuldu kontrolleri yapıldı
![Resim1](https://user-images.githubusercontent.com/62549695/224557715-df399013-b552-4aa0-aa73-45a7db8ba595.png)
![Resim2](https://user-images.githubusercontent.com/62549695/224557720-4a9170cd-3686-48e8-9aac-5c4c82d6107a.png)
